import type { LeadInputs } from "./types";
import { enrichLead } from "./decision-engine";

// 8 leads designed to exercise every branch of the decision engine.
// Each scenario tests a specific business logic path from the spec.
const rawLeads: LeadInputs[] = [
  // --- Scenario 1: Ideal borrower — all 3 pillars strong ---
  {
    id: "lead-001",
    firstName: "Kenji",
    lastName: "Tanaka",
    email: "k.tanaka@email.com",
    phone: "(832) 555-0188",
    createdAt: "2026-04-12T08:45:00Z",
    lastUpdated: "2026-04-16T10:12:00Z",
    createdBy: "Diana Reyes",
    assignedTo: "Diana Reyes",
    leadSource: "REFERRAL_PAST_CLIENT",
    creditRange: "740_PLUS",
    annualGrossIncome: "150K_PLUS",
    monthlyDebtPayments: 300,
    cashAvailable: "60K_PLUS",
    employmentType: "SELF_EMPLOYED_FILED",
    occupancyIntent: "PRIMARY_HOME",
    hasFiledTaxes: true,
    heavyWriteOffs: false,
    targetPurchasePrice: 675000,
    status: "approved",
    notes: "Ideal client. Owed taxes — strong reported income. Ready to go.",
  },

  // --- Scenario 2: FHA-ready borrower (standard W-2, meets all minimums) ---
  {
    id: "lead-002",
    firstName: "Amanda",
    lastName: "Foster",
    email: "amanda.f@email.com",
    phone: "(713) 555-0119",
    createdAt: "2026-04-13T15:10:00Z",
    lastUpdated: "2026-04-15T09:30:00Z",
    createdBy: "intake_form",
    assignedTo: "Marcus Lee",
    leadSource: "WEBSITE_FORM",
    creditRange: "680_739",
    annualGrossIncome: "60K_90K",
    monthlyDebtPayments: 550,
    cashAvailable: "15K_30K",
    employmentType: "W2",
    occupancyIntent: "PRIMARY_HOME",
    targetPurchasePrice: 295000,
    status: "new",
    notes: "First-time buyer. FHA should work cleanly.",
  },

  // --- Scenario 3: 580+ credit but weak cash (DPA candidate) ---
  {
    id: "lead-003",
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@email.com",
    phone: "(713) 555-0104",
    createdAt: "2026-04-15T09:15:00Z",
    lastUpdated: "2026-04-15T09:15:00Z",
    createdBy: "intake_form",
    assignedTo: "Diana Reyes",
    leadSource: "WEBSITE_FORM",
    creditRange: "580_619",
    annualGrossIncome: "40K_60K",
    monthlyDebtPayments: 350,
    cashAvailable: "5K_15K",
    employmentType: "W2",
    occupancyIntent: "PRIMARY_HOME",
    targetPurchasePrice: 215000,
    status: "reviewed",
    notes:
      "First-time buyer. Credit meets FHA. Cash is tight — explore DPA + seller concessions.",
  },

  // --- Scenario 4: Self-employed, filed, heavy write-offs → Non-QM ---
  {
    id: "lead-004",
    firstName: "Daniel",
    lastName: "Okafor",
    email: "d.okafor@email.com",
    phone: "(832) 555-0177",
    createdAt: "2026-04-15T16:40:00Z",
    lastUpdated: "2026-04-16T11:20:00Z",
    createdBy: "Marcus Lee",
    assignedTo: "Marcus Lee",
    leadSource: "REFERRAL_AGENT",
    creditRange: "680_739",
    annualGrossIncome: "150K_PLUS",
    monthlyDebtPayments: 1200,
    cashAvailable: "60K_PLUS",
    employmentType: "SELF_EMPLOYED_FILED",
    occupancyIntent: "PRIMARY_HOME",
    hasFiledTaxes: true,
    heavyWriteOffs: true,
    targetPurchasePrice: 550000,
    status: "new",
    notes:
      "Small business owner. Writes off aggressively — reported income low. Bank statement loan likely.",
  },

  // --- Scenario 5: Self-employed, NOT filed → Non-QM bank statement ---
  {
    id: "lead-005",
    firstName: "Roberto",
    lastName: "Martinez",
    email: "rob.martinez@email.com",
    phone: "(346) 555-0160",
    createdAt: "2026-04-14T13:28:00Z",
    lastUpdated: "2026-04-14T13:28:00Z",
    createdBy: "Marcus Lee",
    assignedTo: "Marcus Lee",
    leadSource: "REFERRAL_AGENT",
    creditRange: "620_679",
    annualGrossIncome: "90K_150K",
    monthlyDebtPayments: 400,
    cashAvailable: "30K_60K",
    employmentType: "SELF_EMPLOYED_NOT_FILED",
    occupancyIntent: "PRIMARY_HOME",
    hasFiledTaxes: false,
    targetPurchasePrice: 350000,
    status: "new",
    notes:
      "Contractor, two years in business. Unfiled returns — route to Non-QM.",
  },

  // --- Scenario 6: Strong credit + cash, weak DTI (debt too high) ---
  {
    id: "lead-006",
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus.j@email.com",
    phone: "(713) 555-0142",
    createdAt: "2026-04-16T14:22:00Z",
    lastUpdated: "2026-04-16T14:22:00Z",
    createdBy: "intake_form",
    assignedTo: "Diana Reyes",
    leadSource: "WEBSITE_FORM",
    creditRange: "740_PLUS",
    annualGrossIncome: "60K_90K",
    monthlyDebtPayments: 1600,
    cashAvailable: "60K_PLUS",
    employmentType: "W2",
    occupancyIntent: "PRIMARY_HOME",
    targetPurchasePrice: 425000,
    status: "new",
    notes: "Great credit and savings. Debt load is the blocker — pay-down plan.",
  },

  // --- Scenario 7: Mid-credit, tight budget (2-of-3 workable) ---
  {
    id: "lead-007",
    firstName: "Priya",
    lastName: "Shah",
    email: "priya.shah@email.com",
    phone: "(281) 555-0198",
    createdAt: "2026-04-16T11:05:00Z",
    lastUpdated: "2026-04-16T11:05:00Z",
    createdBy: "intake_form",
    assignedTo: "Diana Reyes",
    leadSource: "SOCIAL_MEDIA",
    creditRange: "620_679",
    annualGrossIncome: "60K_90K",
    monthlyDebtPayments: 550,
    cashAvailable: "15K_30K",
    employmentType: "W2",
    occupancyIntent: "PRIMARY_HOME",
    targetPurchasePrice: 280000,
    status: "new",
  },

  // --- Scenario 8: Not ready — credit below 580, high debt, minimal cash ---
  {
    id: "lead-008",
    firstName: "Jessica",
    lastName: "Wright",
    email: "jess.wright@email.com",
    phone: "(281) 555-0133",
    createdAt: "2026-04-14T10:50:00Z",
    lastUpdated: "2026-04-15T12:00:00Z",
    createdBy: "Diana Reyes",
    assignedTo: "Diana Reyes",
    leadSource: "OPEN_HOUSE",
    creditRange: "BELOW_580",
    annualGrossIncome: "40K_60K",
    monthlyDebtPayments: 1100,
    cashAvailable: "UNDER_5K",
    employmentType: "W2",
    occupancyIntent: "PRIMARY_HOME",
    targetPurchasePrice: 200000,
    status: "reviewed",
    notes: "Needs credit repair + debt paydown before application makes sense.",
  },
];

export const mockLeads = rawLeads.map(enrichLead);
